### ISSUE TITLE
$loadScript not working with $router.push

### ISSUE THREAD

**Issue by joshuaTTL** [tserkov/vue-plugin-load-script#10]
Hi! First of all, this is a great library! I'm trying to use it to inject MathJax with my Vuejs project. It works fine with a newly loaded page or a reloaded page. However, if I do a $router.push to another page, even though there is a $loadScript called in the created() method, it returns undefined without loading the library or throwing an error. Can you help me with this matter? Thanks so much!

**Comment by tserkov** [comment]
What kinda of behavior do you see if you use the following minimal snippet?
```javascript
created() {
  this.$loadScript("https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML")
    .then(() => {
      console.log("Successfully loaded MathJax!");
    })
    .catch((err) => {
      console.log("Failed to load MathJax:", err);
    });
},
```
