### ISSUE TITLE
it's not working in IE-11

### ISSUE THREAD

**Issue by Froschkoenig84** [tserkov/vue-plugin-load-script#12]
In Chrome or FireFox everything works fine. But IE-11 

There is creates a syntax error in app.js :/
![image](https://user-images.githubusercontent.com/49907406/65420352-36f6fa80-de01-11e9-8d1f-c01cf99c89f6.png)

I use it like this:
![image](https://user-images.githubusercontent.com/49907406/65420470-89d0b200-de01-11e9-9463-8f3b81bcbf73.png)

**Comment by tserkov** [comment]
This plugin is written in ES6, which IE11 doesn't support -- you'll need to transpile it using Babel or similar.
