### ISSUE TITLE
Race Condition

### ISSUE THREAD

**Issue by bendytree** [tserkov/vue-plugin-load-script#13]
When this code tries to [detect whether the script has been loaded](https://github.com/tserkov/vue-plugin-load-script/blob/master/index.js#L5) yet, it checks if the script is on the DOM, not whether it's actually loaded.

Since the script is being loaded `async`, there's a decent chance a second call would resolve before the script has actually loaded.

**Comment by tserkov** [comment]
I don't believe a race condition exists there. That line exists to prevent duplicate `<script>` elements for the same source.

Loading does not begin until the `<script>` element is injected into the DOM.  The attribute `async` has no effect on this behavior.

With that said, I do see a potential for improvement in the error/abort event handlers by removing the `<script>` element before rejecting the Promise, so failures don't prevent future successes.

**Comment by bendytree** [comment]
Here's an example:
https://codesandbox.io/s/vue-template-mjdoz?fontsize=14

If `loadScript` is called multiple times with the same url, the subsequent calls will find the DOM element and immediately resolve (even though the script may not have actually loaded yet).

**Comment by tserkov** [comment]
Thank you for the example, I hadn't anticipated that usage.

I have a solution in mind that involves tracking script resolvers manually, since `HTMLScriptElement` is fairly dumb in regards to its current status. It'll take me a few days to get around to it though.

**Comment by victornpb** [comment]
I created this PR https://github.com/tserkov/vue-plugin-load-script/pull/18
