### ISSUE TITLE
npm and yarn install

### ISSUE THREAD

**Issue by duduklein** [tserkov/vue-plugin-load-script#14]
Why do you suggest to install the package as "npm install --save-dev" or "yarn add --dev".

If the code is executed in production, we should add it without the dev parameters, correct?

**Comment by tserkov** [comment]
Absolutely correct. That was a drunk commit that I partially corrected a while back; if you look at the Github readme it's been fixed for a while, I just haven't published it to npm.

**Comment by duduklein** [comment]
Thanks. And sorry for missing it. I'm closing this issue.
