### ISSUE TITLE
[Object Object]

### ISSUE THREAD

**Issue by aytacmalkoc** [tserkov/vue-plugin-load-script#22]
Hi, I can import scripts properly, but it creates a script element between head tags as below. This causes an error on the console. I wonder what's the solution?

`<script type="text/javascript" async="" src="[object Object]" data-loaded="true"></script>`

**Comment by tserkov** [comment]
Double-check what you're setting as the source -- it needs to be a string
containing the URI/path to the script you're trying to load.
