### ISSUE TITLE
What about CompositionAPI import?

### ISSUE THREAD

**Issue by professrr** [tserkov/vue-plugin-load-script#23]
How to import something like `loadScript` using the Composition API?

**Comment by tserkov** [comment]
I personally haven't made the switch yet.  Looking at the documentation, supporting Vue 3 may be backwards compatible, so I'll take a crack at it.

**Comment by bisubus** [comment]
From #20, it would be as simple as `const useLoadScript = () => ({ loadScript, unloadScript })`, although there's no reason to have a hook for the sake of hook. Named exports are enough because it doesn't do anything specific to component instance.

**Comment by Bjornar97** [comment]
Composition API is now supported in vue 3. Added in #20
