### ISSUE TITLE
Can't import when using Nuxt

### ISSUE THREAD

**Issue by zx-81-16k** [tserkov/vue-plugin-load-script#26]
I have Vue 2.x and nuxt application.

When i import from npm package i'm getting "Unexpected token export".

When i copied code from github and put in ordinary .js file and import that - everything is ok

Any ideas ?

**Comment by tserkov** [comment]
Unfortunately, I don't use Nuxt myself, but the following configuration  may resolve your issue -- let me know if it works!

```javascript
// nuxt.config.js
module.exports = {
  // ...
  build: {
    transpile: ['vue-plugin-load-script']
  }
  // ...
};
```
Reference: [NuxtJS - ES6 Plugins](https://nuxtjs.org/docs/2.x/directory-structure/plugins/#es6-plugins)

**Comment by zx-81-16k** [comment]
Yes! It worked :)
Thank you a lot for your help!
