### ISSUE TITLE
Installation error with Vue 3 - Cannot set property "$loadScript" of undefined

### ISSUE THREAD

**Issue by DaDoBaag** [tserkov/vue-plugin-load-script#27]
When trying to use this package with Vue 3 I get the TypeError mentioned above. I followed the installation guide for Vue 3 which states to use `npm install --save vue-plugin-load-script@">=2.0.0"` but when I do this my package.json shows a different version:

```
"vue-plugin-load-script": "^1.3.2"
```

I also use typescript but have properly declared the type by doing `declare module 'vue-plugin-load-script';` in my index.d.ts file. My main.ts looks like this:

```js
import { createApp } from 'vue';
import App from './App.vue';
import LoadScript from 'vue-plugin-load-script';

const app = createApp(App).use(LoadScript);

app.mount('#app');
```

What is wrong here?

**Comment by Bjornar97** [comment]
Can you try to change the version manually to "^2.1.0" in package.json, and do `npm update`.

**Comment by Bjornar97** [comment]
I see now that the 2.1.0 version hasnt been tagged, so try changing to `^2.0.1`

**Comment by DaDoBaag** [comment]
> I see now that the 2.1.0 version hasnt been tagged, so try changing to `^2.0.1`

Yes this worked, thank you. Any idea why it didn't install the correct version by itself? I specified it in the install command after all.

**Comment by Bjornar97** [comment]
> Yes this worked, thank you. Any idea why it didn't install the correct version by itself? I specified it in the install command after all.

I dont know. I tested it myself and for me it did install the correct version, so I have no idea.

**Comment by DaDoBaag** [comment]
Ok. Maybe it was an error on my part. Who knows.
