### ISSUE TITLE
Type definition in v1.3.4 overrides local Vue type definitions

### ISSUE THREAD

**Issue by tonythomson** [tserkov/vue-plugin-load-script#30]
The type definition added in v1.3.4 in `index.d.ts` prevents any local declaration of of "vue/types/vue" from being loaded.

When I upgraded from vue-plugin-load-script v1.3.3 to v1.3.4, my build started breaking with complaints that my injected services on the Vue instance were not valid properties. My type definition file to define custom properties on the Vue instance has stopped having any effect. If I manually delete the code
```
declare module "vue/types/vue" {
  interface Vue {
    $loadScript: (src: string) => Promise<HTMLScriptElement>;
    $unloadScript: (src: string) => Promise<void>;
  }
}
```
from this package's `index.d.ts` file, my own file will load again, allowing my build to succeed again.

It's my understanding that this type definition on the Vue object should be left to the consumer of the package, but if there's something I'm missing, I'd be happy to be wrong.

**Comment by tserkov** [comment]
H:i @tonythomson, I'm sorry to hear that!

According to the [Vue documentation](https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins) and [Typescript documentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation):
> 1. You can’t declare new top-level declarations in the augmentation — just patches to existing declarations.

This also how other plugins implement typings: [example 1](https://github.com/pagekit/vue-resource/blob/develop/types/vue.d.ts#L14-L26) [example 2](https://github.com/kazupon/vue-i18n/blob/v8.x/types/index.d.ts#L270-L279)

So I'm not entirely sure how this is technically possible.  Would you be able to provide a minimal example that reproduces the issue?

Thanks!

**Comment by tonythomson** [comment]
Thanks for the links, @tserkov ! They gave me some examples with which to regress. Neither of those libraries, when imported into my project, causes the same error. I believe I've tracked down the difference.

In the typings file for `vue-plugin-load-script`, we are missing the import statement for Vue, listed by the Vue docs linked above as necessary. If I put the import at the top into the module's typings file, my compilation errors disappear.

Not a TS expert, but I believe that what is happening is that without the import, my local type defs are defined on the Vue object, then when the module's types are loaded, if the import is present, the types are applied to augment the already-augmented Vue instance. Without the import statement, the type definitions is applied to the original Vue object, losing any interim type definitions. Regardless of reason, restoring the import fixes things. I'll open a PR for your consideration.

**Comment by tserkov** [comment]
🤦🏻‍♂️ oof, such a rookie mistake! Thanks for catching that, I'm looking at the PR now. :)
