### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by balap777** [tserkov/vue-plugin-load-script#32]
getting this error in vuejs 3 for v2.*
![image](https://user-images.githubusercontent.com/42376010/145450598-715d606c-d687-43a3-901f-f2ab2786d1c8.png)

**Comment by AmmarMohamadIsmaeel** [comment]
Me too, getting same error, any updates?

**Comment by leosolid** [comment]
Did you find a fix or alternative library?

**Comment by tserkov** [comment]
Hi all, it looks like I forgot to tag and publish `2.1.0` which properly supports Vue 3. Please run `npm install vue-plugin-load-script@">=2.1.0"` which should fix this!

Thanks!
