### ISSUE TITLE
2022 - Plugin no longer works at all, this should be archived

### ISSUE THREAD

**Issue by slothentic** [tserkov/vue-plugin-load-script#34]
Neither method works now, waste of time

**Comment by tserkov** [comment]
Hi @slothentic, sorry to hear you're having trouble using the plugin!

While your issue doesn't give anything in the way of details into your problem, I took some time to create a couple of Vue 2 & 3 projects to see if anything was wrong with the README, and there was an issue with versioning for Vue 2 installation!

I've updated the README and published [v1.3.6](https://github.com/tserkov/vue-plugin-load-script/releases/tag/v1.3.6), which should fix any issues you were having. Please re-open if this isn't the case.

Thanks.
