### ISSUE TITLE
Prevent duplicate script loads

### ISSUE THREAD

**Issue by cliffordh** [tserkov/vue-plugin-load-script#4]
If I want to include the same script from two different components that exist on the same page it would be great if the scripts were not loaded twice.

**Comment by tserkov** [comment]
The scripts should not be loaded twice if the paths they are loaded from are exactly the same, thanks to the following lines:

https://github.com/tserkov/vue-plugin-load-script/blob/a7bb8847141b7cca0786e651868476b227ab49d7/index.js#L5-L9

Are you seeing the same script loaded multiple times?
