### ISSUE TITLE
Unexpected token error on mounting js file

### ISSUE THREAD

**Issue by anistark** [tserkov/vue-plugin-load-script#6]
I'm getting `Uncaught SyntaxError: Unexpected token <` for the following inclusion in my `App.vue` file.

```
export default {
    name: 'app',
    components: {
        Home
    },
    created () {
        this.$loadScript("./assets/js/home.js");
    }
}

```

How do I fix it?

**Comment by tserkov** [comment]
My best guess is that `./assets/js/home.js` is not resolving to a JavaScript file, but instead to an HTML file. Check the network requests in your dev console.

**Comment by anistark** [comment]
@tserkov How do we pass a js file then?

Any pointers or link to look it up?

**Comment by tellamon** [comment]
@anistark Do you find any solution? I'm suffering the same error but the file is still js file.

**Comment by tellamon** [comment]
I put my js file into the public folder and the problem is solved.

refer https://stackoverflow.com/a/54002260
