### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by MarioEisold** [tserkov/vue-plugin-load-script#7]
I have just set up a new Vue CLI3 project and installed the load-script plugin. I have also copied the code into my main.js and linked it to jquery. Right away I get an error:

Could not find a declaration file for module 'vue-plugin-load-script'. '/Users/me/Documents/_Private/_Projects/_TECH/vue-test03/node_modules/vue-plugin-load-script/index.js' implicitly has an 'any' type.
  Try `npm install @types/vue-plugin-load-script` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-plugin-load-script';`

I have then tried to run: npm install @types/vue-plugin-load-script
Error:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: idb-connector@1.1.8 (node_modules/idb-connector):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for idb-connector@1.1.8: wanted {"os":"aix","arch":"any"} (current: {"os":"darwin","arch":"x64"})

Any help is appreciated.

**Comment by tserkov** [comment]
It looks like this is a TypeScript issue.  This plugin doesn't provide any TypeScript definition files, as I don't personally use it.  If you'd like to, I'd love it if you were to create a definition file for this plugin and submit a PR!

**Comment by mubasshir** [comment]
for others, create a `index.d.ts` file inside src/types and paster following
`declare module 'vue-plugin-load-script';`

**Comment by SlavMFM** [comment]
@mubasshir thanks, but error now changed to:

> Property 'loadScript' does not exist on type 'VueConstructor<Vue>'

**Comment by Dezzley** [comment]
@SlavMFM you may create another declaration file, let's say `load-script.d.ts` and extend the interface VueConsturctor like this:
```
import Vue from 'vue';

declare module 'vue/types/vue' {
  interface VueConstructor {
    loadScript: Function
  }
}
```

You can read more about augmentation here https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins
